### ISSUE TITLE
Build Fails: undefined: x509.CertificateRequest

### ISSUE THREAD

**Issue by johscheuer** [coreos/etcd-ca#48]
Hey,

Im trying to build etcd-ca on Ubuntu Utopic with go 1.2.1:
```
go version go1.2.1 linux/amd64
```
and I get this error:
```
~/Development/workspace/etcd-ca$ ./build 
Building etcd-ca
# github.com/coreos/etcd-ca/pkix
src/github.com/coreos/etcd-ca/pkix/csr.go:89: undefined: x509.CertificateRequest
```

I am using golang from Ubuntu Repository. I found this issue (another repo) https://github.com/cloudflare/cfssl/issues/36 where it says

> Unfortunately, certificate requests were introduced in Go 1.3;

https://github.com/coreos/etcd-ca/blob/master/README.md#building the go Version should be changed from 1.2+ to 1.3+?

After update to go 1.4.1 and a new git clone everything works perfectly.

**Comment by yichengq** [comment]
fixed by #49
