### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by rufman** [coreos/etcd-ca#53]
I tried building etcd-ca with the latest golang Docker images and got the following error: gopath/src/github.com/coreos/etcd-ca/cmd/util.go:11:2: code in directory /go/etcd-ca/gopath/src/github.com/coreos/etcd-ca/Godeps/_workspace/src/golang.org/x/crypto/ssh/terminal expects import "golang.org/x/crypto/ssh/terminal"

**Comment by rufman** [comment]
This commit (dcff62519def8664c8a42dca156fe47ee08ff8d9) works, but commits (ec29b3ad590b730d91bf9f38439e81326abe4bd0) and above that don't. I don't really know go, but I'm assuming it has something to do with the godeps PR merge.

**Comment by yichengq** [comment]
I think the latest master has fixed this problem. Could you try current master: https://github.com/coreos/etcd/commit/84dac75ed560216e54f40f3a377b0ba5d8340784 ?

**Comment by fourcube** [comment]
@yichengq I have just cloned etcd-ca and I am getting the same error as @rufman.

**Comment by fourcube** [comment]
Changing https://github.com/coreos/etcd-ca/blob/master/Godeps/_workspace/src/golang.org/x/crypto/ssh/terminal/util.go#L17

From

```go
package terminal // import "golang.org/x/crypto/ssh/terminal"
```

to 

```go
package terminal // import "github.com/coreos/etcd-ca/Godeps/_workspace/src/golang.org/x/crypto/ssh/terminal"
```

fixes the build for me. Is this a problem of godep?

**Comment by yichengq** [comment]
@fourcube This is really weird. I want to fix it but i cannot reproduce it at all.

```
unihorn@CoreOS /tmp> mkdir gopath
unihorn@CoreOS /tmp> export GOPATH=/tmp/gopath
unihorn@CoreOS /tmp> cd gopath
unihorn@CoreOS /t/gopath> go get github.com/coreos/etcd-ca
unihorn@CoreOS /t/gopath> cd src/github.com/coreos/etcd-ca
unihorn@CoreOS /t/g/s/g/c/etcd-ca> ./build
unihorn@CoreOS /t/g/s/g/c/etcd-ca> ./bin/etcd-ca
```

and it works well for me.

**Comment by rufman** [comment]
I'm still getting the same error, so I think @fourcube might be right about godep.

@yichengq 
I used the latest docker image for golang to build and manage the ca, instead of installing go on my system:
```
docker pull golang
docker run -i -t golang /bin/bash
git clone https://github.com/coreos/etcd-ca
cd etcd-ca
./build
```

**Comment by fourcube** [comment]
@yichengq I just replicated your session on my box and the error is the same.

```
fourcube@devbox:/tmp$ mkdir gopath
fourcube@devbox:/tmp$ export GOPATH=/tmp/gopath
fourcube@devbox:/tmp$ cd gopath
fourcube@devbox:/tmp/gopath$ go get github.com/coreos/etcd-ca
src/github.com/coreos/etcd-ca/cmd/util.go:11:2: code in directory /tmp/gopath/src/github.com/coreos/etcd-ca/Godeps/_workspace/src/golang.org/x/crypto/ssh/terminal expects import "golang.org/x/crypto/ssh/terminal"
```

I'm using the following go version.
```
fourcube@devbox:~$ go version
go version go1.4.1 linux/amd64
```

**Comment by fourcube** [comment]
I have just verified that this also fails on my Mac.

**Comment by yichengq** [comment]
Fixed. I think go1.4 changes the behavior of this and my godep doesn't do it correctly.
Thanks for the report and fix way. @fourcube
