### ISSUE TITLE
Can't Sign Generated  Cert Using etcd-ca

### ISSUE THREAD

**Issue by akamalov** [coreos/etcd-ca#56]
For some reason, etcd-ca can't stat the file it created.

Generate certs:

root@0947d9ea9a4d:/go/etcd-ca/bin# ./etcd-ca new-cert --organization "MyOrg" --country "US" --ip 10.0.0.10 server1.mydomain.com                        
Enter passphrase (empty for no passphrase): *******
Enter same passphrase again: *******
Created server1.mydomain.com/key
Created server1.mydomain.com/crt

Go ahead and sign the cert:

root@0947d9ea9a4d:/go/etcd-ca/bin# ./etcd-ca sign server1.mydomain.com     
Get CA certificate error: stat /go/etcd-ca/bin/.etcd-ca/ca.crt: no such file or directory

root@0947d9ea9a4d:/go/etcd-ca/bin# pwd
/go/etcd-ca/bin

root@0947d9ea9a4d:/go/etcd-ca/bin# ls -al .etcd-ca/
total 24
drwxr-xr-x 2 root root 4096 Apr 13 15:44 .
drwxr-xr-x 3 root root 4096 Apr 13 15:30 ..
-r--r--r-- 1 root root 1708 Apr 13 15:44 server1.mydomain.com.host.csr
-r--r----- 1 root root 3311 Apr 13 15:44 server1.mydomain.com.host.key
root@0947d9ea9a4d:/go/etcd-ca/bin# 

root@0947d9ea9a4d:/go/etcd-ca/bin# go version
go version go1.4.2 linux/amd64
root@0947d9ea9a4d:/go/etcd-ca/bin#

**Comment by akamalov** [comment]
Anyone is working on it ?

**Comment by yichengq** [comment]
@akamalov Will work on it this week.

**Comment by akamalov** [comment]
Thanks Yicheng!

**Comment by yichengq** [comment]
@akamalov I find it cannot work because user should do `./etcd-ca init` first. But it certainly deserves a better error message.
Reference: https://github.com/coreos/etcd-ca#create-a-new-certificate-authority

**Comment by yichengq** [comment]
@akamalov Have time to give it a try?

**Comment by akamalov** [comment]
Just tested. Yes, it does work. My bad. I don't know how I skipped "etcd-ca init."

Thanks again!!!

Alex
